name: 'ci'
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          ado_org: philip-gai
          ado_project: github-ado-chatops
          ado_repo: github-ado-chatops
          ado_pat: ${{ secrets.ADO_PAT }}